-- The access rules exactly as they were before 20261009_performance_rls_indexes.sql, in case they
-- ever need to be put back. Not run automatically.
alter policy ads_delete on public.ad_campaigns using (is_admin());
alter policy ads_insert on public.ad_campaigns with check (((app_role() IS NOT NULL) AND (created_by = auth.uid()) AND (is_staff() OR (payer_type = 'recruiter'::text) OR (status = 'Pending approval'::text))));
alter policy ads_read on public.ad_campaigns using ((is_staff() OR ((app_role() = 'recruiter'::text) AND (created_by = auth.uid()))));
alter policy ads_update on public.ad_campaigns using (is_staff()) with check (is_staff());
alter policy settings_read on public.agency_settings using ((app_role() IS NOT NULL));
alter policy settings_write on public.agency_settings using (is_admin()) with check (is_admin());
alter policy apps_staff on public.applications using (is_staff()) with check (is_staff());
alter policy audit_insert on public.audit_log with check ((actor_id = auth.uid()));
alter policy audit_read on public.audit_log using (is_admin());
alter policy camp_delete on public.campaigns using (is_admin());
alter policy camp_insert on public.campaigns with check (((app_role() IS NOT NULL) AND (created_by = auth.uid())));
alter policy camp_read on public.campaigns using ((app_role() IS NOT NULL));
alter policy camp_update on public.campaigns using ((is_staff() OR (created_by = auth.uid()))) with check ((is_staff() OR (created_by = auth.uid())));
alter policy comments_insert on public.candidate_comments with check (((author_id = auth.uid()) AND (EXISTS ( SELECT 1 FROM candidates c WHERE (c.id = candidate_comments.candidate_id)))));
alter policy cjmsg_insert on public.candidate_job_messages with check (((sender = 'recruiter'::text) AND (author_id = auth.uid()) AND (is_staff() OR (EXISTS ( SELECT 1 FROM (candidate_jobs cj JOIN candidates c ON ((c.id = cj.candidate_id))) WHERE ((cj.id = candidate_job_messages.link_id) AND ((c.recruiter_id = auth.uid()) OR (EXISTS ( SELECT 1 FROM job_recruiters jr WHERE ((jr.job_id = cj.job_id) AND (jr.recruiter_id = auth.uid())))))))))));
alter policy cjmsg_read on public.candidate_job_messages using ((is_staff() OR (EXISTS ( SELECT 1 FROM (candidate_jobs cj JOIN candidates c ON ((c.id = cj.candidate_id))) WHERE ((cj.id = candidate_job_messages.link_id) AND ((c.recruiter_id = auth.uid()) OR (EXISTS ( SELECT 1 FROM job_recruiters jr WHERE ((jr.job_id = cj.job_id) AND (jr.recruiter_id = auth.uid()))))))))));
alter policy cjmsg_update on public.candidate_job_messages using ((is_staff() OR (EXISTS ( SELECT 1 FROM (candidate_jobs cj JOIN candidates c ON ((c.id = cj.candidate_id))) WHERE ((cj.id = candidate_job_messages.link_id) AND ((c.recruiter_id = auth.uid()) OR (EXISTS ( SELECT 1 FROM job_recruiters jr WHERE ((jr.job_id = cj.job_id) AND (jr.recruiter_id = auth.uid())))))))))) with check ((is_staff() OR (EXISTS ( SELECT 1 FROM (candidate_jobs cj JOIN candidates c ON ((c.id = cj.candidate_id))) WHERE ((cj.id = candidate_job_messages.link_id) AND ((c.recruiter_id = auth.uid()) OR (EXISTS ( SELECT 1 FROM job_recruiters jr WHERE ((jr.job_id = cj.job_id) AND (jr.recruiter_id = auth.uid()))))))))));
alter policy cj_delete on public.candidate_jobs using (is_staff());
alter policy cj_read on public.candidate_jobs using ((is_staff() OR (EXISTS ( SELECT 1 FROM candidates c WHERE ((c.id = candidate_jobs.candidate_id) AND (c.recruiter_id = auth.uid())))) OR (EXISTS ( SELECT 1 FROM job_recruiters jr WHERE ((jr.job_id = candidate_jobs.job_id) AND (jr.recruiter_id = auth.uid()))))));
alter policy cj_update on public.candidate_jobs using ((is_staff() OR (EXISTS ( SELECT 1 FROM candidates c WHERE ((c.id = candidate_jobs.candidate_id) AND (c.recruiter_id = auth.uid())))))) with check ((is_staff() OR (EXISTS ( SELECT 1 FROM candidates c WHERE ((c.id = candidate_jobs.candidate_id) AND (c.recruiter_id = auth.uid()))))));
alter policy cj_write on public.candidate_jobs with check ((is_staff() OR (EXISTS ( SELECT 1 FROM candidates c WHERE ((c.id = candidate_jobs.candidate_id) AND (c.recruiter_id = auth.uid()))))));
alter policy cand_delete on public.candidates using (is_admin());
alter policy cand_insert on public.candidates with check ((is_staff() OR ((app_role() = 'recruiter'::text) AND (recruiter_id = auth.uid()))));
alter policy cand_read on public.candidates using (((recruiter_id = auth.uid()) OR (is_staff() AND (NOT is_draft))));
alter policy cand_update on public.candidates using (((recruiter_id = auth.uid()) OR (is_staff() AND (NOT is_draft)))) with check (((recruiter_id = auth.uid()) OR (is_staff() AND (NOT is_draft))));
alter policy chat_clears_own on public.chat_clears using ((viewer = (auth.uid())::text));
alter policy interviews_delete on public.interviews using ((is_staff() OR (recruiter_id = auth.uid())));
alter policy jeng_insert on public.job_engagements with check ((recruiter_id = auth.uid()));
alter policy jeng_read on public.job_engagements using ((is_staff() OR (recruiter_id = auth.uid())));
alter policy jeng_update on public.job_engagements using (((recruiter_id = auth.uid()) OR is_staff())) with check (((recruiter_id = auth.uid()) OR is_staff()));
alter policy jobrec_read on public.job_recruiters using ((app_role() IS NOT NULL));
alter policy jobrec_write on public.job_recruiters using ((is_staff() OR (recruiter_id = auth.uid()))) with check ((is_staff() OR (recruiter_id = auth.uid())));
alter policy jobs_delete on public.jobs using (is_admin());
alter policy jobs_insert on public.jobs with check (((app_role() IS NOT NULL) AND (created_by = auth.uid())));
alter policy jobs_read on public.jobs using ((app_role() IS NOT NULL));
alter policy jobs_update on public.jobs using ((is_staff() OR (created_by = auth.uid()))) with check ((is_staff() OR (created_by = auth.uid())));
alter policy leads_staff on public.leads using (is_staff()) with check (is_staff());
alter policy outreach_messages_staff_read on public.outreach_messages using (is_staff());
alter policy suppressions_staff_read on public.outreach_suppressions using (is_staff());
alter policy place_read on public.placements using ((is_staff() OR ((app_role() = 'recruiter'::text) AND (recruiter_id = auth.uid()))));
alter policy place_write on public.placements using (is_staff()) with check (is_staff());
alter policy "admin or self can read profile_security" on public.profile_security using (((user_id = auth.uid()) OR (EXISTS ( SELECT 1 FROM profiles p WHERE ((p.id = auth.uid()) AND (p.role = 'admin'::text) AND (p.status = 'Active'::text))))));
alter policy profiles_admin_write on public.profiles using (is_admin()) with check (is_admin());
alter policy profiles_read on public.profiles using (((id = auth.uid()) OR (app_role() IS NOT NULL)));
alter policy profiles_self_update on public.profiles using ((id = auth.uid())) with check ((id = auth.uid()));
alter policy prospects_staff on public.prospects using (is_staff()) with check (is_staff());
alter policy spend_requests_staff_read on public.spend_requests using (is_staff());
